package com.demeter.cloud.model.mapper;

import com.demeter.cloud.model.entity.AdminUserExt;
import com.demeter.cloud.model.entity.AdminUserExtExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminUserExtMapper {
    long countByExample(AdminUserExtExample example);

    int deleteByExample(AdminUserExtExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(AdminUserExt record);

    int insertSelective(AdminUserExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_admin_user_ext
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    AdminUserExt selectOneByExample(AdminUserExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_admin_user_ext
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    AdminUserExt selectOneByExampleSelective(@Param("example") AdminUserExtExample example, @Param("selective") AdminUserExt.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_admin_user_ext
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<AdminUserExt> selectByExampleSelective(@Param("example") AdminUserExtExample example, @Param("selective") AdminUserExt.Column ... selective);

    List<AdminUserExt> selectByExample(AdminUserExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_admin_user_ext
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    AdminUserExt selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AdminUserExt.Column ... selective);

    AdminUserExt selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_admin_user_ext
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    AdminUserExt selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") AdminUserExt record, @Param("example") AdminUserExtExample example);

    int updateByExample(@Param("record") AdminUserExt record, @Param("example") AdminUserExtExample example);

    int updateByPrimaryKeySelective(AdminUserExt record);

    int updateByPrimaryKey(AdminUserExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_admin_user_ext
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") AdminUserExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_admin_user_ext
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}