package com.demeter.cloud.model.mapper;

import com.demeter.cloud.model.entity.PublicParameter;
import com.demeter.cloud.model.entity.PublicParameterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PublicParameterMapper {
    long countByExample(PublicParameterExample example);

    int deleteByExample(PublicParameterExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(PublicParameter record);

    int insertSelective(PublicParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_public_parameter
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PublicParameter selectOneByExample(PublicParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_public_parameter
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PublicParameter selectOneByExampleSelective(@Param("example") PublicParameterExample example, @Param("selective") PublicParameter.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_public_parameter
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<PublicParameter> selectByExampleSelective(@Param("example") PublicParameterExample example, @Param("selective") PublicParameter.Column ... selective);

    List<PublicParameter> selectByExample(PublicParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_public_parameter
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PublicParameter selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") PublicParameter.Column ... selective);

    PublicParameter selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_public_parameter
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PublicParameter selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") PublicParameter record, @Param("example") PublicParameterExample example);

    int updateByExample(@Param("record") PublicParameter record, @Param("example") PublicParameterExample example);

    int updateByPrimaryKeySelective(PublicParameter record);

    int updateByPrimaryKey(PublicParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_public_parameter
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") PublicParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_public_parameter
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}