package com.demeter.cloud.model.mapper;

import com.demeter.cloud.model.entity.UsageRecord;
import com.demeter.cloud.model.entity.UsageRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsageRecordMapper {
    long countByExample(UsageRecordExample example);

    int deleteByExample(UsageRecordExample example);

    int deleteByPrimaryKey(String id);

    int insert(UsageRecord record);

    int insertSelective(UsageRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_usage_record
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UsageRecord selectOneByExample(UsageRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_usage_record
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UsageRecord selectOneByExampleSelective(@Param("example") UsageRecordExample example, @Param("selective") UsageRecord.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_usage_record
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<UsageRecord> selectByExampleSelective(@Param("example") UsageRecordExample example, @Param("selective") UsageRecord.Column ... selective);

    List<UsageRecord> selectByExample(UsageRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_usage_record
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UsageRecord selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") UsageRecord.Column ... selective);

    UsageRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_usage_record
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UsageRecord selectByPrimaryKeyWithLogicalDelete(@Param("id") String id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") UsageRecord record, @Param("example") UsageRecordExample example);

    int updateByExample(@Param("record") UsageRecord record, @Param("example") UsageRecordExample example);

    int updateByPrimaryKeySelective(UsageRecord record);

    int updateByPrimaryKey(UsageRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_usage_record
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") UsageRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_usage_record
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(String id);
}