package com.demeter.cloud.model.mapper;

import com.demeter.cloud.model.entity.VoteInfo;
import com.demeter.cloud.model.entity.VoteInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VoteInfoMapper {
    long countByExample(VoteInfoExample example);

    int deleteByExample(VoteInfoExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(VoteInfo record);

    int insertSelective(VoteInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_vote_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    VoteInfo selectOneByExample(VoteInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_vote_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    VoteInfo selectOneByExampleSelective(@Param("example") VoteInfoExample example, @Param("selective") VoteInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_vote_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<VoteInfo> selectByExampleSelective(@Param("example") VoteInfoExample example, @Param("selective") VoteInfo.Column ... selective);

    List<VoteInfo> selectByExample(VoteInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_vote_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    VoteInfo selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") VoteInfo.Column ... selective);

    VoteInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_vote_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    VoteInfo selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") VoteInfo record, @Param("example") VoteInfoExample example);

    int updateByExample(@Param("record") VoteInfo record, @Param("example") VoteInfoExample example);

    int updateByPrimaryKeySelective(VoteInfo record);

    int updateByPrimaryKey(VoteInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_vote_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") VoteInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_vote_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}