package com.demeter.cloud.model.mapper;

import com.demeter.cloud.model.entity.WorksInfo;
import com.demeter.cloud.model.entity.WorksInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WorksInfoMapper {
    long countByExample(WorksInfoExample example);

    int deleteByExample(WorksInfoExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(WorksInfo record);

    int insertSelective(WorksInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_works_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    WorksInfo selectOneByExample(WorksInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_works_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    WorksInfo selectOneByExampleSelective(@Param("example") WorksInfoExample example, @Param("selective") WorksInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_works_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<WorksInfo> selectByExampleSelective(@Param("example") WorksInfoExample example, @Param("selective") WorksInfo.Column ... selective);

    List<WorksInfo> selectByExample(WorksInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_works_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    WorksInfo selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") WorksInfo.Column ... selective);

    WorksInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_works_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    WorksInfo selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") WorksInfo record, @Param("example") WorksInfoExample example);

    int updateByExample(@Param("record") WorksInfo record, @Param("example") WorksInfoExample example);

    int updateByPrimaryKeySelective(WorksInfo record);

    int updateByPrimaryKey(WorksInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_works_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") WorksInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_works_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}