package com.demeter.cloud.model.mapper;

import com.demeter.cloud.model.entity.ActivityTemplate;
import com.demeter.cloud.model.entity.ActivityTemplateExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ActivityTemplateMapper {
    long countByExample(ActivityTemplateExample example);

    int deleteByExample(ActivityTemplateExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(ActivityTemplate record);

    int insertSelective(ActivityTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_activity_template
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ActivityTemplate selectOneByExample(ActivityTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_activity_template
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ActivityTemplate selectOneByExampleSelective(@Param("example") ActivityTemplateExample example, @Param("selective") ActivityTemplate.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_activity_template
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ActivityTemplate> selectByExampleSelective(@Param("example") ActivityTemplateExample example, @Param("selective") ActivityTemplate.Column ... selective);

    List<ActivityTemplate> selectByExample(ActivityTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_activity_template
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ActivityTemplate selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ActivityTemplate.Column ... selective);

    ActivityTemplate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_activity_template
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ActivityTemplate selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") ActivityTemplate record, @Param("example") ActivityTemplateExample example);

    int updateByExample(@Param("record") ActivityTemplate record, @Param("example") ActivityTemplateExample example);

    int updateByPrimaryKeySelective(ActivityTemplate record);

    int updateByPrimaryKey(ActivityTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_activity_template
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ActivityTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_activity_template
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}