package com.demeter.cloud.model.mapper;

import com.demeter.cloud.model.entity.BrowseInfo;
import com.demeter.cloud.model.entity.BrowseInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BrowseInfoMapper {
    long countByExample(BrowseInfoExample example);

    int deleteByExample(BrowseInfoExample example);

    int deleteByPrimaryKey(String id);

    int insert(BrowseInfo record);

    int insertSelective(BrowseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_browse_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BrowseInfo selectOneByExample(BrowseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_browse_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BrowseInfo selectOneByExampleSelective(@Param("example") BrowseInfoExample example, @Param("selective") BrowseInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_browse_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<BrowseInfo> selectByExampleSelective(@Param("example") BrowseInfoExample example, @Param("selective") BrowseInfo.Column ... selective);

    List<BrowseInfo> selectByExample(BrowseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_browse_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BrowseInfo selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") BrowseInfo.Column ... selective);

    BrowseInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_browse_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BrowseInfo selectByPrimaryKeyWithLogicalDelete(@Param("id") String id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") BrowseInfo record, @Param("example") BrowseInfoExample example);

    int updateByExample(@Param("record") BrowseInfo record, @Param("example") BrowseInfoExample example);

    int updateByPrimaryKeySelective(BrowseInfo record);

    int updateByPrimaryKey(BrowseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_browse_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") BrowseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_browse_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(String id);
}