package com.demeter.cloud.model.mapper;

import com.demeter.cloud.model.entity.ConfigParameter;
import com.demeter.cloud.model.entity.ConfigParameterExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ConfigParameterMapper {
    long countByExample(ConfigParameterExample example);

    int deleteByExample(ConfigParameterExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(ConfigParameter record);

    int insertSelective(ConfigParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_config_parameter
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ConfigParameter selectOneByExample(ConfigParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_config_parameter
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ConfigParameter selectOneByExampleSelective(@Param("example") ConfigParameterExample example, @Param("selective") ConfigParameter.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_config_parameter
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ConfigParameter> selectByExampleSelective(@Param("example") ConfigParameterExample example, @Param("selective") ConfigParameter.Column ... selective);

    List<ConfigParameter> selectByExample(ConfigParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_config_parameter
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ConfigParameter selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ConfigParameter.Column ... selective);

    ConfigParameter selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_config_parameter
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ConfigParameter selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") ConfigParameter record, @Param("example") ConfigParameterExample example);

    int updateByExample(@Param("record") ConfigParameter record, @Param("example") ConfigParameterExample example);

    int updateByPrimaryKeySelective(ConfigParameter record);

    int updateByPrimaryKey(ConfigParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_config_parameter
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ConfigParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_config_parameter
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}