package com.demeter.cloud.model.mapper;

import com.demeter.cloud.model.entity.EnrollInfo;
import com.demeter.cloud.model.entity.EnrollInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EnrollInfoMapper {
    long countByExample(EnrollInfoExample example);

    int deleteByExample(EnrollInfoExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(EnrollInfo record);

    int insertSelective(EnrollInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_enroll_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    EnrollInfo selectOneByExample(EnrollInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_enroll_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    EnrollInfo selectOneByExampleSelective(@Param("example") EnrollInfoExample example, @Param("selective") EnrollInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_enroll_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<EnrollInfo> selectByExampleSelective(@Param("example") EnrollInfoExample example, @Param("selective") EnrollInfo.Column ... selective);

    List<EnrollInfo> selectByExample(EnrollInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_enroll_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    EnrollInfo selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") EnrollInfo.Column ... selective);

    EnrollInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_enroll_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    EnrollInfo selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") EnrollInfo record, @Param("example") EnrollInfoExample example);

    int updateByExample(@Param("record") EnrollInfo record, @Param("example") EnrollInfoExample example);

    int updateByPrimaryKeySelective(EnrollInfo record);

    int updateByPrimaryKey(EnrollInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_enroll_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") EnrollInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_enroll_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}