package com.demeter.cloud.model.mapper;

import com.demeter.cloud.model.entity.LikeInfo;
import com.demeter.cloud.model.entity.LikeInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LikeInfoMapper {
    long countByExample(LikeInfoExample example);

    int deleteByExample(LikeInfoExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(LikeInfo record);

    int insertSelective(LikeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_like_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LikeInfo selectOneByExample(LikeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_like_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LikeInfo selectOneByExampleSelective(@Param("example") LikeInfoExample example, @Param("selective") LikeInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_like_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LikeInfo> selectByExampleSelective(@Param("example") LikeInfoExample example, @Param("selective") LikeInfo.Column ... selective);

    List<LikeInfo> selectByExample(LikeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_like_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LikeInfo selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LikeInfo.Column ... selective);

    LikeInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_like_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LikeInfo selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") LikeInfo record, @Param("example") LikeInfoExample example);

    int updateByExample(@Param("record") LikeInfo record, @Param("example") LikeInfoExample example);

    int updateByPrimaryKeySelective(LikeInfo record);

    int updateByPrimaryKey(LikeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_like_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LikeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_like_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}