package com.demeter.cloud.model.mapper;

import com.demeter.cloud.model.entity.StorageFile;
import com.demeter.cloud.model.entity.StorageFileExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface StorageFileMapper {
    long countByExample(StorageFileExample example);

    int deleteByExample(StorageFileExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(StorageFile record);

    int insertSelective(StorageFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_storage_file
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    StorageFile selectOneByExample(StorageFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_storage_file
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    StorageFile selectOneByExampleSelective(@Param("example") StorageFileExample example, @Param("selective") StorageFile.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_storage_file
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<StorageFile> selectByExampleSelective(@Param("example") StorageFileExample example, @Param("selective") StorageFile.Column ... selective);

    List<StorageFile> selectByExample(StorageFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_storage_file
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    StorageFile selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") StorageFile.Column ... selective);

    StorageFile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_storage_file
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    StorageFile selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") StorageFile record, @Param("example") StorageFileExample example);

    int updateByExample(@Param("record") StorageFile record, @Param("example") StorageFileExample example);

    int updateByPrimaryKeySelective(StorageFile record);

    int updateByPrimaryKey(StorageFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_storage_file
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") StorageFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demeter_storage_file
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}