demeter:
  cloud:
    # 对象存储配置
    storage:
      # 当前工作的对象存储模式，分别是local、aliyun、tencent、qiniu,minio
      active: minio
      # 本地对象存储配置信息
      local:
        # 这个地方应该是wx模块的WxStorageController的fetch方法对应的地址
        address: http://localhost:8080/demo/storage/
        storage-path: app/fileupload
        # 阿里云对象存储配置信息
      aliyun:
        access-key-id: LTAI4G2Pn5ztxA2rRgFMJsoh
        access-key-secret: LFybagHCTfujIH47Rl0PemfF2xGzaD
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket-name: develop-platform
        # 腾讯对象存储配置信息
        # 请参考 https://cloud.tencent.com/document/product/436/6249
      tencent:
        access-key-id: 111111
        access-key-secret: xxxxxx
        endpoint: xxxxxx
        bucket-name: dcloud
        # 七牛云对象存储配置信息
      qiniu:
        access-key-id: 111111
        access-key-secret: xxxxxx
        bucket-name: dcloud
        endpoint: http://dcloud.clouddn.com
      minio:
        access-key-id: root
        access-key-secret: PandoraCloud@2020
        bucket-name: developer-cloud
        endpoint: http://139.9.40.63:9999/


pagehelper:
  helperDialect:  mysql
  reasonable: true
  supportMethodsArguments:  true
  params: count=countSql

#  数据库连接池配置
spring:
  datasource:
    url:  jdbc:mysql://139.9.40.63:3306/demeter-cloud-platform?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false&allowPublicKeyRetrieval=true
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: PandoraCloud@2020
    druid:
      url: jdbc:mysql://139.9.40.63:3306/demeter-cloud-platform?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username:  root
      password:  PandoraCloud@2020
      initial-size:  10
      max-active:  50
      min-idle:  10
      max-wait:  60000
      pool-prepared-statements:  true
      max-pool-prepared-statement-per-connection-size:  20
      validation-query:  SELECT 1 FROM DUAL
      test-on-borrow:  false
      test-on-return:  false
      test-while-idle:  true
      time-between-eviction-runs-millis:  60000
      filters:  stat,wall
  redis:
    port: 6379
    database: 0
    host: 139.9.40.63
    password: PandoraCloud@2020
    timeout: 20000
    lettuce:
      pool:
       max-active: 8
       min-idle: 0
       max-idle: 8
       max-wait: -1
