dts:
  # 开发者应该设置成自己的wx相关信息
  wx:
    app-id: wxbaca3ef15b7fe688
    app-secret: 6752a10e4980e36594bb6a61b3557d70
    mch-id: 1534075311
    mch-key: 7788819wode1984chun1234567890123
    notify-url: https://www.shunyingxin.com/program/wx/order/redirect
    # 商户证书文件路径
    # 请参考“商户证书”一节 https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=4_3
    key-path: apiclient_cert.p12

  #通知相关配置
  notify:
    mail:
      # 邮件通知配置,邮箱一般用于接收业务通知例如收到新的订单，sendto 定义邮件接收者，通常为商城运营人员
      enable: true
      host: smtp.aliyun.com
      username: dtsshop@aliyun.com
      password: xxx
      sendfrom: xxx@aliyun.com
      sendto: xxx@qq.com

    # 短消息模版通知配置
    # 短信息用于通知客户，例如发货短信通知，注意配置格式；template-name，template-templateId 请参考 NotifyType 枚举值
    sms:
      enable: true
      appid: 1400286323
      appkey: 223123sade14c129c4ce9a30b5f90ad2c
      template:
        - name: paySucceed
          templateId: 112233
        - name: captcha
          templateId: 112233
        - name: ship
          templateId: 112233
        - name: refund
          templateId: 112233

    # 微信模版通知配置
    # 微信模版用于通知客户或者运营者，注意配置格式；template-name，template-templateId 请参考 NotifyType 枚举值
    wx:
      enable: true
      template:
        - name: paySucceed
          templateId: R1ct58-H1EMfw_THXM1_icZoC63QTdkBf2tt7W89MYo
        - name: captcha
          templateId: BHiUxkvaZSxgmIUgPl7nDUhN29znWW6ImbPz5PFIrzg
        - name: ship
          templateId: ygQlVFC0qdXvalNbZtLTYik6r443k4nOUHE4ckx6q5I
        - name: applyRefund
          templateId: JNxFlFF-b0N00hob4lLt0i-rsX7eDYOWnkF1vo8eC-w
        - name: refund
          templateId: WUUTPWpAexfgFovcFH0_gokwAmIuN3_onn231nT55vs
        - name: refund
          templateId: h2KAsVmz5QjEkRQs6sbkox3yUv-8v8imwtuhKHLgXck

  # 快鸟物流查询配置
  express:
    enable: true
    appId: "1689622"
    appKey: "2527aee1-a0b8-445c-b63f-1ca140c87bdb"
    vendors:
      - code: "HTKY"
        name: "百世快递"
      - code: "YZBK"
        name: "邮政国内标快"
      - code: "ZTO"
        name: "中通快递"
      - code: "YTO"
        name: "圆通速递"
      - code: "YD"
        name: "韵达速递"
      - code: "YZPY"
        name: "邮政快递包裹"
      - code: "EMS"
        name: "EMS"
      - code: "DBL"
        name: "德邦快递"
      - code: "FAST"
        name: "快捷快递"
      - code: "ZJS"
        name: "宅急送"
      - code: "TNT"
        name: "TNT快递"
      - code: "UPS"
        name: "UPS"
      - code: "DHL"
        name: "DHL"
      - code: "FEDEX"
        name: "FEDEX联邦(国内件)"
      - code: "FEDEX_GJ"
        name: "FEDEX联邦(国际件)"

  # 对象存储配置
  storage:
    # 当前工作的对象存储模式，分别是local、aliyun、tencent、qiniu
    active: aliyun
    # 本地对象存储配置信息
    local:
      storagePath: app/fileupload
      # 这个地方应该是wx模块的WxStorageController的fetch方法对应的地址
      address: http://localhost:8080/demo/storage/
    # 阿里云对象存储配置信息
    aliyun:
      endpoint: oss-cn-beijing.aliyuncs.com
      accessKeyId: 
      accessKeySecret: 
      bucketName: develop-platform
    # 腾讯对象存储配置信息
    # 请参考 https://cloud.tencent.com/document/product/436/6249
    tencent:
      secretId: 111111
      secretKey: xxxxxx
      region: xxxxxx
      bucketName: dts
    # 七牛云对象存储配置信息
    qiniu:
      endpoint: http://dtsshop.wx.clouddn.com
      accessKey: 111111
      secretKey: xxxxxx
      bucketName: dts

pagehelper:
  helperDialect:  mysql
  reasonable: true
  supportMethodsArguments:  true
  params: count=countSql

#  数据库连接池配置
spring:
  datasource:
    url:  jdbc:mysql://101.200.217.19:3307/mall-cloud-platform?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false&allowPublicKeyRetrieval=true
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: MallPlatform@2020
    druid:
      url: jdbc:mysql://101.200.217.19:3307/mall-cloud-platform?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username:  root
      password:  MallPlatform@2020
      initial-size:  10
      max-active:  50
      min-idle:  10
      max-wait:  60000
      pool-prepared-statements:  true
      max-pool-prepared-statement-per-connection-size:  20
      validation-query:  SELECT 1 FROM DUAL
      test-on-borrow:  false
      test-on-return:  false
      test-while-idle:  true
      time-between-eviction-runs-millis:  60000
      filters:  stat,wall
  redis:
        port: 6380
        database: 0
        host: 101.200.217.19
        password: 1234560@Abc
        timeout: 20000
        lettuce:
          pool:
            max-active: 8
            min-idle: 0
            max-idle: 8
            max-wait: -1
