demeter:
  cloud:
   # 对象存储配置
   storage:
    # 当前工作的对象存储模式，分别是local、aliyun、tencent、qiniu
    active: aliyun
    # 本地对象存储配置信息
    local:
      storagePath: app/fileupload
      # 这个地方应该是wx模块的WxStorageController的fetch方法对应的地址
      address: http://localhost:8080/demo/storage/
    # 阿里云对象存储配置信息
    aliyun:
      endpoint: oss-cn-beijing.aliyuncs.com
      accessKeyId: LTAI4G2Pn5ztxA2rRgFMJsoh
      accessKeySecret: LFybagHCTfujIH47Rl0PemfF2xGzaD
      bucketName: develop-platform
    # 腾讯对象存储配置信息
    # 请参考 https://cloud.tencent.com/document/product/436/6249
    tencent:
      secretId: 111111
      secretKey: xxxxxx
      region: xxxxxx
      bucketName: dts
    # 七牛云对象存储配置信息
    qiniu:
      endpoint: http://dtsshop.wx.clouddn.com
      accessKey: 111111
      secretKey: xxxxxx
      bucketName: dts

pagehelper:
  helperDialect:  mysql
  reasonable: true
  supportMethodsArguments:  true
  params: count=countSql

#  数据库连接池配置
spring:
  datasource:
    url:  jdbc:mysql://139.9.40.63:3306/demeter-cloud-platform?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false&allowPublicKeyRetrieval=true
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: PandoraCloud@2020
    druid:
      url: jdbc:mysql://139.9.40.63:3306/demeter-cloud-platform?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username:  root
      password:  PandoraCloud@2020
      initial-size:  10
      max-active:  50
      min-idle:  10
      max-wait:  60000
      pool-prepared-statements:  true
      max-pool-prepared-statement-per-connection-size:  20
      validation-query:  SELECT 1 FROM DUAL
      test-on-borrow:  false
      test-on-return:  false
      test-while-idle:  true
      time-between-eviction-runs-millis:  60000
      filters:  stat,wall
  redis:
    port: 6379
    database: 0
    host: 139.9.40.63
    password: PandoraCloud@2020
    timeout: 20000
    lettuce:
      pool:
       max-active: 8
       min-idle: 0
       max-idle: 8
       max-wait: -1
