spring:
  profiles:
    active: @profile.active@
  messages:
    encoding: UTF-8
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024
      max-request-size: 1024
      file-size-threshold: 1024
      resolve-lazily: true
  freemarker:
    check-template-location: false
  thymeleaf:
    check-template-location: false

server:
  port: 9002
  compression:
    min-response-size: 1024
  tomcat:
    uri-encoding: UTF-8
    accept-count: 50000
    max-connections: 50000
    connection-timeout: 360000
    threads:
      max: 1024
      min-spare: 100
    max-http-form-post-size: 2048
    max-swallow-size: 2048

#系统日志配置
logging:
  level:
    root:  info
    org.springframework:  info
    org.mybatis:  info
    com.demeter.cloud.console:  info
    com.demeter.cloud.model.mapper:  debug
    com.demeter.cloud:  info
